AWSTemplateFormatVersion: "2010-09-09"
Resources:
  ChatSNSTopic:
    Type: "AWS::SNS::Topic"
    Properties:
      TopicName: "ChatMessagesTopic"
  
  ChatSQSQueue:
    Type: "AWS::SQS::Queue"
    Properties: 
      QueueName: "ChatMessagesQueue"

  ChatSNSSQSPolicy:
    Type: "AWS::SQS::QueuePolicy"
    Properties:
      Queues:
        - !Ref ChatSQSQueue
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal: "*"
            Action: "SQS:SendMessage"
            Resource: !GetAtt ChatSQSQueue.Arn
            Condition:
              ArnEquals:
                aws:SourceArn: !Ref ChatSNSTopic

  ChatSNSSubscription:
    Type: "AWS::SNS::Subscription"
    Properties:
      Endpoint: !GetAtt ChatSQSQueue.Arn
      Protocol: "sqs"
      TopicArn: !Ref ChatSNSTopic

Outputs:
  SNSTopicARN:
    Description: "The ARN of the SNS Topic"
    Value: !Ref ChatSNSTopic

  SQSQueueURL:
    Description: "The URL of the SQS Queue"
    Value: !Ref ChatSQSQueue

